### ISSUE TITLE
ERROR TypeError: undefined is not an object (evaluating 'this.cast.requestSession')

### ISSUE THREAD

**Issue by fitnexus** [dahfazz/ngCast#5]
Hi i keep getting the error "ERROR TypeError: undefined is not an object (evaluating 'this.cast.requestSession')" when trying to run on an ios emulator and device. 
i can see the cast button show up but whenever i try to click it i get this message in my log. 
if i'm testing using ionic serve on the browser the button opens up the cast alert but nothing seems to work when testing  on a ios device

please any help would be useful.

**Comment by dahfazz** [comment]
Hi @fitnexus 
thanks for your contribution
I admit I did not work on ngCast for a looong time but your engagement make me feel I should restart next week

for the moment, I saw there: https://github.com/dahfazz/ngCast/blob/61365b639ab1fe342f59323e23702b98a76c5655/shared/ng-cast.service.ts#L22

that my code seems to be written for Chrome users...

I should look for safari/ff support

Thanks again and keep in touch
